/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import pronostics.Equipe;

import sql.SQLConnection;

/**
 *
 * @author k1fryouf
 */
public class AddMatch extends javax.swing.JFrame {

    private SQLConnection myConnection;
    private ChampionatUI parent;
    /**
     * Creates new form AddMatch
     */
    public AddMatch(SQLConnection myConnection, ChampionatUI parent) {
        this.myConnection = myConnection;
        this.parent = parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextStade = new javax.swing.JTextField();
        jTextFieldComp = new javax.swing.JTextField();
        jButtonAjouter = new javax.swing.JButton();
        jButtonFermer = new javax.swing.JButton();
        jButtonEffacerTout = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        jTextDate = new javax.swing.JTextField();
        jTextButDom = new javax.swing.JTextField();
        jTextButExt = new javax.swing.JTextField();
        jTextEquipeDom = new javax.swing.JComboBox();
        jTextEquipeExt = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Équipe Domicile ");

        jLabel2.setText("Date");

        jLabel3.setText("Équipe Extérieure");

        jLabel4.setText("Stade");

        jLabel5.setText("Compétition");

        jButtonAjouter.setText("Ajouter");
        jButtonAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjouterActionPerformed(evt);
            }
        });

        jButtonFermer.setText("Fermer");
        jButtonFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFermerActionPerformed(evt);
            }
        });

        jButtonEffacerTout.setText("Effacer tout");
        jButtonEffacerTout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEffacerToutActionPerformed(evt);
            }
        });

        jLabel6.setText("ID :");

        myConnection.setTableName("APP.EQUIPES");
        ArrayList<Equipe> equipes = myConnection.selectTeamsByComp(parent.getChampionat());
        ArrayList<String> s = new ArrayList<>();
        for(Equipe e : equipes){
            s.add(e.getNom());
        }
        jTextEquipeDom.setModel(new javax.swing.DefaultComboBoxModel(s.toArray(new String[s.size()])));

        jTextEquipeExt.setModel(new javax.swing.DefaultComboBoxModel(s.toArray(new String[s.size()])));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jButtonAjouter)
                            .addGap(79, 79, 79)
                            .addComponent(jButtonEffacerTout)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonFermer))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(274, 274, 274)
                            .addComponent(jLabelId)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(154, 154, 154))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(105, 105, 105)))
                        .addComponent(jTextFieldComp, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextStade)
                            .addComponent(jTextDate)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextEquipeExt, 0, 201, Short.MAX_VALUE)
                                    .addComponent(jTextEquipeDom, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextButExt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextButDom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel6)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextButDom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextEquipeDom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextButExt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextEquipeExt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextStade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelId)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAjouter)
                    .addComponent(jButtonEffacerTout)
                    .addComponent(jButtonFermer))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFermerActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonFermerActionPerformed

    private void jButtonEffacerToutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEffacerToutActionPerformed
        jTextEquipeDom.setSelectedIndex(0);
        jTextEquipeExt.setSelectedIndex(0);
        jTextFieldComp.setText("");
        jTextDate.setText("");
        jTextStade.setText("");
    }//GEN-LAST:event_jButtonEffacerToutActionPerformed

    private void jButtonAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjouterActionPerformed

        myConnection.setTableName("APP.MATCHES");
        
        if ("Ajouter".equals(jButtonAjouter.getText())){
            boolean result = myConnection.insertMatch(
                    "("+jTextEquipeDom.getSelectedItem().toString().substring(0, 3)+
                            jTextEquipeExt.getSelectedItem().toString().substring(0, 3)+
                            jTextDate.getText()+")",
                            jTextEquipeDom.getSelectedItem().toString(),
                            jTextEquipeExt.getSelectedItem().toString(),
                            jTextStade.getText(),
                            jTextDate.getText(),
                            jTextFieldComp.getText(),
                            Integer.parseInt(jTextButDom.getText()),
                            Integer.parseInt(jTextButExt.getText()));

            if(result == true){

                parent.refreshListMatchs(parent.getChampionat());
            }else{
                JOptionPane.showMessageDialog(this, "Erreur !");
            }
            jTextEquipeDom.setSelectedIndex(0);
            jTextEquipeExt.setSelectedIndex(0);
            jTextButDom.setText("");
            jTextButExt.setText("");
            jTextStade.setText("");
            jTextDate.setText("");
            jTextFieldComp.setText("");

        }else if ("Modifier".equals(jButtonAjouter.getText())){

            boolean result = myConnection.editMatch(jLabelId.getText(),
                    jTextEquipeDom.getSelectedItem().toString(),
                    jTextEquipeExt.getSelectedItem().toString(),
                    jTextStade.getText(),
                    jTextDate.getText(),
                    jTextFieldComp.getText(),
                    Integer.parseInt(jTextButDom.getText()),
                    Integer.parseInt(jTextButExt.getText()));

            if(result){
                parent.refreshListMatchs(parent.getChampionat());
                JOptionPane.showMessageDialog(this, "Modifié");
            }else{
                JOptionPane.showMessageDialog(this, "Erreur");
            }
        }
       
       parent.refreshListMatchs(parent.getChampionat());
        
    }//GEN-LAST:event_jButtonAjouterActionPerformed

    public JButton getjButtonAjouter() {
        return jButtonAjouter;
    }

    public void setjButtonAjouter(JButton jButtonAjouter) {
        this.jButtonAjouter = jButtonAjouter;
    }

    public JTextField getjTextComp() {
        return jTextFieldComp;
    }

    public void setjTextComp(JTextField jTextComp) {
        this.jTextFieldComp = jTextComp;
    }

    public JTextField getjTextDate() {
        return jTextDate;
    }

    public void setjTextDate(JTextField jTextDate) {
        this.jTextDate = jTextDate;
    }

    public JComboBox getjTextEquipeDom() {
        return jTextEquipeDom;
    }

    public void setjTextEquipeDom(JComboBox jTextEquipeDom) {
        this.jTextEquipeDom = jTextEquipeDom;
    }

    public JComboBox getjTextEquipeExt() {
        return jTextEquipeExt;
    }

    public void setjTextEquipeExt(JComboBox jTextEquipeExt) {
        this.jTextEquipeExt = jTextEquipeExt;
    }

    public JTextField getjTextStade() {
        return jTextStade;
    }

    public void setjTextStade(JTextField jTextStade) {
        this.jTextStade = jTextStade;
    }

    public JLabel getjLabelId() {
        return jLabelId;
    }

    public void setjLabelId(JLabel jLabelId) {
        this.jLabelId = jLabelId;
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAjouter;
    private javax.swing.JButton jButtonEffacerTout;
    private javax.swing.JButton jButtonFermer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JTextField jTextButDom;
    private javax.swing.JTextField jTextButExt;
    private javax.swing.JTextField jTextDate;
    private javax.swing.JComboBox jTextEquipeDom;
    private javax.swing.JComboBox jTextEquipeExt;
    private javax.swing.JTextField jTextFieldComp;
    private javax.swing.JTextField jTextStade;
    // End of variables declaration//GEN-END:variables
}
