package gui;

import java.awt.event.KeyEvent;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import sql.SQLConnection;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author k1fryouf
 */
public class AddTeam extends javax.swing.JFrame {

    private SQLConnection myConnection;
    private ChampionatUI parent;
    /**
     * Creates new form AddTeam
     * @param myConnection
     * @param parent
     */
    public AddTeam(SQLConnection myConnection, ChampionatUI parent) {
        this.parent = parent;
        this.myConnection = myConnection;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonFermer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextNom = new javax.swing.JTextField();
        jTextStade = new javax.swing.JTextField();
        jTextPays = new javax.swing.JTextField();
        jTextEntraineur = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextChampionat = new javax.swing.JTextField();
        jTextPresident = new javax.swing.JTextField();
        jTextIcon = new javax.swing.JTextField();
        jButtonAjouter = new javax.swing.JButton();
        jButtonEffacerTout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonFermer.setText("Fermer");
        jButtonFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFermerActionPerformed(evt);
            }
        });

        jLabel1.setText("Nom");

        jLabel2.setText("Entraineur");

        jLabel3.setText("Stade");

        jLabel4.setText("Pays");

        jTextEntraineur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEntraineurActionPerformed(evt);
            }
        });

        jLabel5.setText("Championat");

        jLabel6.setText("Icon");

        jLabel7.setText("President");

        jButtonAjouter.setText("Ajouter");
        jButtonAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjouterActionPerformed(evt);
            }
        });

        jButtonEffacerTout.setText("Effacer tout");
        jButtonEffacerTout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEffacerToutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAjouter)
                        .addGap(34, 34, 34)
                        .addComponent(jButtonEffacerTout)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(jButtonFermer))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextEntraineur, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextPays, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextNom, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextStade, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextPresident, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextChampionat, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextPays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextEntraineur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextStade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextChampionat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextPresident, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFermer)
                    .addComponent(jButtonAjouter)
                    .addComponent(jButtonEffacerTout))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFermerActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonFermerActionPerformed

    private void jTextEntraineurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEntraineurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextEntraineurActionPerformed

    private void jButtonAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjouterActionPerformed
        
        if ("Ajouter".equals(jButtonAjouter.getText())){
            boolean result = myConnection.insertTeam(jTextNom.getText(), 
                                                jTextPresident.getText(), 
                                                jTextEntraineur.getText(), 
                                                jTextPays.getText(), 
                                                jTextChampionat.getText(), 
                                                jTextStade.getText(), 
                                                jTextIcon.getText());

            if(result == true){

                parent.refreshListEquipes(parent.getChampionat());
                JOptionPane.showMessageDialog(this, "Ajouté");
            }else{
                JOptionPane.showMessageDialog(this, "Erreur !");
            } 
            jTextNom.setText("");
            jTextPays.setText("");
            jTextEntraineur.setText("");
            jTextStade.setText("");
            jTextPresident.setText("");
            jTextIcon.setText("");
        }else if ("Modifier".equals(jButtonAjouter.getText())){
            
            boolean result = myConnection.editTeam(jTextNom.getText(), 
                                                jTextPresident.getText(), 
                                                jTextEntraineur.getText(), 
                                                jTextPays.getText(), 
                                                jTextChampionat.getText(), 
                                                jTextStade.getText(), 
                                                jTextIcon.getText());
            
            if(result){
                parent.refreshListEquipes(parent.getChampionat());
                JOptionPane.showMessageDialog(this, "Modifié");
            }else{
                JOptionPane.showMessageDialog(this, "Erreur");
            }
        }
    }//GEN-LAST:event_jButtonAjouterActionPerformed

    private void jButtonEffacerToutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEffacerToutActionPerformed
        jTextNom.setText("");
        jTextPays.setText("");
        jTextEntraineur.setText("");
        if(parent.getName().equals("jButtonAutres"))
            jTextChampionat.setText("");
        jTextStade.setText("");
        jTextPresident.setText("");
        jTextIcon.setText("");
    }//GEN-LAST:event_jButtonEffacerToutActionPerformed

    public JButton getjButtonAjouter() {
        return jButtonAjouter;
    }

    public void setjButtonAjouter(JButton jButtonAjouter) {
        this.jButtonAjouter = jButtonAjouter;
    }

    public JTextField getjTextChampionat() {
        return jTextChampionat;
    }

    public void setjTextChampionat(JTextField jTextChampionat) {
        this.jTextChampionat = jTextChampionat;
    }

    public JTextField getjTextEntraineur() {
        return jTextEntraineur;
    }

    public void setjTextEntraineur(JTextField jTextEntraineur) {
        this.jTextEntraineur = jTextEntraineur;
    }

    public JTextField getjTextIcon() {
        return jTextIcon;
    }

    public void setjTextIcon(JTextField jTextIcon) {
        this.jTextIcon = jTextIcon;
    }

    public JTextField getjTextNom() {
        return jTextNom;
    }

    public void setjTextNom(JTextField jTextNom) {
        this.jTextNom = jTextNom;
    }

    public JTextField getjTextPays() {
        return jTextPays;
    }

    public void setjTextPays(JTextField jTextPays) {
        this.jTextPays = jTextPays;
    }

    public JTextField getjTextPresident() {
        return jTextPresident;
    }

    public void setjTextPresident(JTextField jTextPresident) {
        this.jTextPresident = jTextPresident;
    }

    public JTextField getjTextStade() {
        return jTextStade;
    }

    public void setjTextStade(JTextField jTextStade) {
        this.jTextStade = jTextStade;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAjouter;
    private javax.swing.JButton jButtonEffacerTout;
    private javax.swing.JButton jButtonFermer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextChampionat;
    private javax.swing.JTextField jTextEntraineur;
    private javax.swing.JTextField jTextIcon;
    private javax.swing.JTextField jTextNom;
    private javax.swing.JTextField jTextPays;
    private javax.swing.JTextField jTextPresident;
    private javax.swing.JTextField jTextStade;
    // End of variables declaration//GEN-END:variables
}
