/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jeu;

import java.io.File;


/**
 *
 * @author k1fryouf
 */
public class MenuInterface extends javax.swing.JFrame {

    /**
     * Creates new form FenetrePrincipale
     */
    MenuControleur menu;
    public MenuInterface() {
        
        menu = new MenuControleur();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bataille Navale");
        setMinimumSize(new java.awt.Dimension(310, 410));
        getContentPane().setLayout(null);

        jButton1.setText("Nouvelle Partie");
        jButton1.setActionCommand("NouvellePartie");
        jButton1.setName(""); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(91, 90, 126, 48);

        jButton2.setText("Charger une partie");
        getContentPane().add(jButton2);
        jButton2.setBounds(91, 187, 126, 48);

        jButton3.setText("Quitter");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(91, 278, 126, 48);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/image_menu.png").getPath()));
        jLabel1.setMaximumSize(new java.awt.Dimension(850, 410));
        jLabel1.setMinimumSize(new java.awt.Dimension(850, 410));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 310, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        menu.demarrerPartieVsIA();
        PartieInterface fenetre = new PartieInterface();
        fenetre.setVisible(true);
  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}